spring.application.name=ficha
server.port=${PORT:8080}
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always